# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('ide', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_documented', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Deteriorating', 'Deteriorating'), ('In Remission', 'In Remission'), ('Active', 'Active'), ('Resolved', 'Resolved')], max_length=255)),
            ],
        ),
    ]
