# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScripeAlpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snomed',
            name='initials',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
